"""add snils and telephone

Revision ID: e42f62e00b5f
Revises: 11a337710606
Create Date: 2023-05-12 23:48:25.020248

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e42f62e00b5f'
down_revision = '11a337710606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('snils', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('users', sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'snils')
    # ### end Alembic commands ###
